import { getCourseIdBySearch } from '../libs/course-handler';

import fs from 'fs';
import path from 'path';


type CourseWithUni = {
    name: string;
    university: string;
}
const courses: CourseWithUni[] = [
    { name: "3D打印技术及应用", university: "西北工业大学" },
    { name: "App Inventor-零基础Android移动应用开发", university: "浙大城市学院" },
    { name: "C语言程序设计CAP", university: "浙江大学" },
    { name: "C语言程序设计CAP", university: "浙江大学" },
    { name: "C语言程序设计", university: "浙江大学" },
    { name: "C语言程序设计精髓", university: "哈尔滨工业大学" },
    { name: "Java程序设计", university: "北京大学" },
    { name: "Linux开发环境及应用", university: "北京邮电大学" },
    { name: "Linux操作系统编程", university: "电子科技大学" },
    { name: "Python语言程序设计", university: "北京理工大学" },
    { name: "Python语言程序设计", university: "北京理工大学" },
    { name: "Python语言程序设计", university: "北京理工大学" },
    { name: "Python语言程序设计", university: "北京理工大学" },
    { name: "Web前端开发", university: "北京林业大学" },
    { name: "web应用开发", university: "常州工业职业技术学院" },
    { name: "android智能手机编程", university: "国家开放大学" },
    { name: "Web前端开发", university: "北京林业大学" },
    { name: `"爱上广告"——广告艺术鉴赏`, university: "南京邮电大学" },
    { name: "中国传统节日与养生文化", university: "山东中医药大学" },
    { name: "中国古代文学（五）", university: "南京师范大学" },
    { name: "中国古代文学（六）", university: "南京师范大学" },
    { name: "中国古代文学（五）", university: "南京师范大学" },
    { name: "中国哲学", university: "北京师范大学" },
    { name: "中国当代文学", university: "北京大学" },
    { name: "中国文化概论", university: "武汉大学" },
    { name: "中国文化概论", university: "武汉大学" },
    { name: "中国茶文化与茶健康", university: "浙江大学" },
    { name: "中国行政法原理及应用", university: "南京大学" },
    { name: "中学物理教学设计", university: "华南师范大学" },
    { name: "文学经典导读", university: "东北师范大学" },
    { name: "习近平新时代中国特色社会主义思想概论", university: "复旦大学" },
    { name: "二维动画制作", university: "湖南科技学院" },
    { name: "互联网金融概论", university: "中央财经大学" },
    { name: "交互式界面设计", university: "西安邮电大学" },
    { name: "人体解剖生理学", university: "西北工业大学" },
    { name: "人工智能实践：Tensorflow笔记", university: "北京大学" },
    { name: "人工智能实践：Tensorflow笔记", university: "北京大学" },
    { name: "人工智能导论", university: "浙江工业大学" },
    { name: "会计学基础", university: "哈尔滨工业大学" },
    { name: "心理咨询的理论与方法：会谈技巧", university: "南京大学" },
    { name: "传感器与测试技术", university: "国防科技大学" },
    { name: "传感器原理及应用", university: "北京信息科技大学" },
    { name: "传感器与测试技术", university: "国防科技大学" },
    { name: "传播学概论", university: "华东师范大学" },
    { name: "体育概论", university: "华南师范大学" },
    { name: "信号与系统", university: "北京交通大学" },
    { name: "信号与系统", university: "北京交通大学" },
    { name: "信号与系统", university: "北京交通大学" },
    { name: "信息化教学能力之五项修炼", university: "爱课程" },
    { name: "信息素养：效率提升与终身学习的新引擎", university: "四川师范大学" },
    { name: "儿童保健学—从新手爸妈到育儿专家", university: "山东大学" },
    { name: "儿童保健学—从新手爸妈到育儿专家", university: "山东大学" },
    { name: "儿童发展", university: "沈阳师范大学" },
    { name: "数字图像处理", university: "武汉大学" },
    { name: "全球传播", university: "上海外国语大学" },
    { name: "公文写作规范", university: "黑龙江大学" },
    { name: "分子生物学", university: "西安交通大学" },
    { name: "分析化学", university: "中国地质大学（武汉）" },
    { name: "创业营销十步流程", university: "哈尔滨工程大学" },
    { name: "力学(下)", university: "吉林大学" },
    { name: "力学(上)", university: "吉林大学" },
    { name: "力学(上)", university: "吉林大学" },
    { name: "力学(上)", university: "吉林大学" },
    { name: "力学(下)", university: "吉林大学" },
    { name: "功能食品学", university: "陕西理工大学" },
    { name: "动植物检疫", university: "北京林业大学" },
    { name: "动物学", university: "北京师范大学" },
    { name: "动物学", university: "华中农业大学" },
    { name: "动物生物学", university: "武汉大学" },
    { name: "化妆设计基础---自我化妆提升术", university: "浙江纺织服装职业技术学院" },
    { name: "化学课程与教学论", university: "江西师范大学" },
    { name: "区域经济学", university: "北京林业大学" },
    { name: "医用发育生物学", university: "北京大学" },
    { name: "半导体物理与器件原理", university: "复旦大学" },
    { name: "单片机原理及接口技术", university: "安阳师范学院" },
    { name: "大学生心理健康漫谈", university: "东北大学" },
    { name: "发展心理学", university: "北京大学" },
    { name: "发展心理学", university: "北京大学" },
    { name: "发展心理学", university: "北京大学" },
    { name: "发展心理学", university: "北京大学" },
    { name: "口译入门", university: "南京理工大学" },
    { name: "口译理论与实践", university: "北京科技大学" },
    { name: "口语与写作", university: "浙江理工大学" },
    { name: "古代汉语", university: "北京语言大学" },
    { name: "可视化程序设计技术及应用", university: "东北大学" },
    { name: "商业银行经营学", university: "上海财经大学" },
    { name: "固体物理学", university: "北京交通大学" },
    { name: "固体物理学", university: "福州大学" },
    { name: "地图学", university: "南京师范大学" },
    { name: "地球资源与环境信息技术前沿", university: "电子科技大学" },
    { name: "地球资源与环境信息技术前沿", university: "电子科技大学" },
    { name: "城市与文化遗产", university: "华中科技大学" },
    { name: "城市环境地学", university: "华东师范大学" },
    { name: "城市设计原理", university: "西安建筑科技大学" },
    { name: "基因工程", university: "浙江大学" },
    { name: "基础免疫学", university: "北京理工大学" },
    { name: "基础教育改革", university: "哈尔滨师范大学" },
    { name: "基础生物化学", university: "西北农林科技大学" },
    { name: "声乐演唱基础", university: "湖南师范大学" },
    { name: "复变函数论", university: "四川大学" },
    { name: "复变函数论", university: "四川大学" },
    { name: "复变函数论", university: "四川大学" },
    { name: "外国文学史（一）", university: "浙江工商大学" },
    { name: "大学思辨英语听力", university: "南京大学" },
    { name: "大学摄影基础", university: "福建师范大学" },
    { name: "大学日语", university: "西安交通大学" },
    { name: "大学物理 I-（力学、相对论、电磁学）", university: "北京交通大学" },
    { name: "大学物理 II-（热学、振动和波、光学、量子）", university: "北京交通大学" },
    { name: "大学物理2：振动与波动、热学", university: "同济大学" },
    { name: "大学物理（力学、电磁学）", university: "中国地质大学（武汉）" },
    { name: "大学物理（力学、电磁学）", university: "中国地质大学（武汉）" },
    { name: "大学物理—振动、波动与光学", university: "北京理工大学" },
    { name: "大学物理实验（II）", university: "北京交通大学" },
    { name: "大学物理实验（I）", university: "北京交通大学" },
    { name: "大学物理（力学、电磁学）", university: "中国地质大学（武汉）" },
    { name: "大学物理（力学、电磁学）", university: "中国地质大学（武汉）" },
    { name: "大学物理（力学、电磁学）", university: "中国地质大学（武汉）" },
    { name: "大学生职业发展与就业指导", university: "福州大学" },
    { name: "大学英语综合课程(一)", university: "国防科技大学" },
    { name: "大学英语综合课程（四）", university: "国防科技大学" },
    { name: "大家弹起来——钢琴即兴伴奏入门", university: "中央音乐学院" },
    { name: "大数据基础与应用", university: "北京理工大学" },
    { name: "媒体大数据挖掘与案例实战", university: "中国传媒大学" },
    { name: "学前儿童健康教育", university: "南京师范大学" },
    { name: "学前儿童游戏", university: "南京特殊教育师范学院" },
    { name: "学前儿童游戏", university: "南京特殊教育师范学院" },
    { name: "学前儿童游戏", university: "南京特殊教育师范学院" },
    { name: "学前教育原理", university: "陕西师范大学" },
    { name: "学术规范与论文写作", university: "电子科技大学" },
    { name: "学术论文文献阅读与机助汉英翻译", university: "重庆大学" },
    { name: "美术教育学", university: "首都师范大学" },
    { name: "实验心理学：学会研究身边的现象", university: "西南交通大学" },
    { name: "德育原理", university: "河南大学" },
    { name: "小学数学教学设计与案例研究", university: "淮阴师范学院" },
    { name: "小学数学教学论", university: "杭州师范大学" },
    { name: "小学数学课程与教学", university: "江苏第二师范学院" },
    { name: "小学生品德发展与道德教育", university: "首都师范大学" },
    { name: "小学语文教学设计", university: "湖南第一师范学院" },
    { name: "课堂管理的方法与艺术", university: "爱课程" },
    { name: "小学课程设计与评价", university: "华南师范大学" },
    { name: "山海经", university: "大连海事大学" },
    { name: "工程伦理", university: "浙江大学" },
    { name: "平面广告设计", university: "黄河水利职业技术学院" },
    { name: "应用写作", university: "华中农业大学" },
    { name: "中国古代建筑艺术", university: "湖南大学" },
    { name: "开天辟地", university: "上海大学" },
    { name: "异常心理学（变态心理学）", university: "首都师范大学" },
    { name: "影像的力量：电视剧历史与美学", university: "南昌大学" },
    { name: "电影概论", university: "河南大学" },
    { name: "微积分基础", university: "北京大学" },
    { name: "微观经济学", university: "西南交通大学" },
    { name: "微观经济学", university: "浙江大学" },
    { name: "心理活动之生理奥妙——生理心理学漫谈", university: "华中师范大学" },
    { name: "思想政治教育学原理", university: "中南大学" },
    { name: "批判性思维", university: "浙江大学" },
    { name: "摄影基础", university: "电子科技大学" },
    { name: "摄影基础", university: "电子科技大学" },
    { name: "操作系统原理", university: "西安交通大学" },
    { name: "教学论", university: "北京师范大学" },
    { name: "教师职业道德", university: "成都大学" },
    { name: "教师职业道德", university: "成都大学" },
    { name: "教师职业道德", university: "成都大学" },
    { name: "教师职业道德", university: "成都大学" },
    { name: "教师职业道德", university: "成都大学" },
    { name: "教师职业道德与教育政策法规", university: "南通大学" },
    { name: "教师职业道德与教育政策法规", university: "南通大学" },
    { name: "教育哲学", university: "陕西师范大学" },
    { name: "教育心理学", university: "华南师范大学" },
    { name: "教育心理学", university: "北京联合大学" },
    { name: "教育心理学", university: "北京联合大学" },
    { name: "教育心理学", university: "北京联合大学" },
    { name: "教育心理学", university: "北京联合大学" },
    { name: "教育心理学", university: "北京联合大学" },
    { name: "教育法治与教师法治素养", university: "北京师范大学" },
    { name: "教育法治与教师法治素养", university: "北京师范大学" },
    { name: "教育法治与教师法治素养", university: "北京师范大学" },
    { name: "教育法治与教师法治素养", university: "北京师范大学" },
    { name: "教育研究方法", university: "西南大学" },
    { name: "教育研究方法", university: "西南大学" },
    { name: "教育研究方法", university: "西南大学" },
    { name: "教育研究方法", university: "西南大学" },
    { name: "微课设计与制作", university: "爱课程" },
    { name: "Photoshop数字图像处理", university: "黄冈师范学院" },
    { name: "数字图像处理", university: "福建师范大学" },
    { name: "数字插画实战", university: "山东大学" },
    { name: "数字电子技术基础", university: "华中科技大学" },
    { name: "数字电路与逻辑设计", university: "华中科技大学" },
    { name: "数字营销：走进智慧的品牌", university: "暨南大学" },
    { name: "数学分析（二）", university: "华东师范大学" },
    { name: "数学模型求解", university: "北京联合大学" },
    { name: "数学物理方法（一）——复变函数的微积分", university: "北京大学" },
    { name: "数学物理方法（二）——无穷级数", university: "北京大学" },
    { name: "数据库原理与应用", university: "北京林业大学" },
    { name: "数据新闻可视化", university: "江西财经大学" },
    { name: "概率论与数理统计", university: "浙江大学" },
    { name: "文化人类学入门与导读", university: "中央民族大学" },
    { name: "文化创意产品设计", university: "湘潭大学" },
    { name: "文学批评与实践", university: "四川大学" },
    { name: "文献管理与信息分析", university: "中国科学技术大学" },
    { name: "新媒体概论", university: "浙江大学" },
    { name: "新媒体编创", university: "中国传媒大学" },
    { name: "新媒体营销", university: "北京联合大学" },
    { name: "新闻评论", university: "重庆大学" },
    { name: "新闻采访学", university: "河南师范大学" },
    { name: "旅游学基础", university: "河南大学" },
    { name: "旅游学基础", university: "河南大学" },
    { name: "市场调查与研究", university: "南京邮电大学" },
    { name: "旅游政策与法规", university: "四川农业大学" },
    { name: "消费者行为学", university: "上海外国语大学" },
    { name: "旅游目的地管理", university: "洛阳师范学院" },
    { name: "节事活动组织管理", university: "无锡城市职业技术学院" },
    { name: "营销策划", university: "北京联合大学" },
    { name: "无机元素化学", university: "吉林大学" },
    { name: "时间序列分析", university: "中南财经政法大学" },
    { name: "普通昆虫学", university: "中国农业大学" },
    { name: "普通昆虫学", university: "中国农业大学" },
    { name: "普通生物学", university: "大连理工大学" },
    { name: "普通话实训与测试", university: "四川大学" },
    { name: "普通逻辑学", university: "河海大学" },
    { name: "智慧课堂教学", university: "爱课程" },
    { name: "智能媒体传播", university: "中国传媒大学" },
    { name: "有机化学", university: "华中科技大学" },
    { name: "有机化学", university: "华中科技大学" },
    { name: "材料科学基础", university: "西安交通大学" },
    { name: "档案管理学", university: "武汉大学" },
    { name: "植物学", university: "西北大学" },
    { name: "植物生理学", university: "华南师范大学" },
    { name: "概率论与数理统计", university: "厦门大学" },
    { name: "概率论与数理统计", university: "厦门大学" },
    { name: "概率论与数理统计", university: "厦门大学" },
    { name: "模拟电子技术基础", university: "华中科技大学" },
    { name: "毛泽东思想和中国特色社会主义理论体系概论", university: "福建农林大学" },
    { name: "毛泽东思想和中国特色社会主义理论体系概论", university: "福建农林大学" },
    { name: "建筑材料", university: "西南交通大学" },
    { name: "消费者行为学", university: "华中农业大学" },
    { name: "激光原理与技术", university: "电子科技大学" },
    { name: "热学", university: "西安交通大学" },
    { name: "中国水印版画", university: "中国美术学院" },
    { name: "物理化学（上）", university: "东北大学" },
    { name: "物理化学（上）", university: "东北大学" },
    { name: "中学物理教学设计", university: "华南师范大学" },
    { name: "特殊儿童发展与学习", university: "南京特殊教育师范学院" },
    { name: "环境监测", university: "东华大学" },
    { name: "现代教育技术", university: "陕西师范大学" },
    { name: "现代教育技术", university: "陕西师范大学" },
    { name: "现代礼仪", university: "湖南大学" },
    { name: "现代礼仪与修养", university: "贵州理工学院" },
    { name: "现代视听节目编导与制作", university: "哈尔滨师范大学" },
    { name: "理论力学", university: "北京师范大学" },
    { name: "生态学", university: "北京师范大学" },
    { name: "电动力学", university: "华南师范大学" },
    { name: "电子商务", university: "重庆大学" },
    { name: "电子技术", university: "北京交通大学" },
    { name: "电子技术", university: "北京交通大学" },
    { name: "电工学", university: "哈尔滨工业大学" },
    { name: "电视采访报道", university: "中国传媒大学" },
    { name: "电路分析", university: "厦门大学" },
    { name: "社会工作概论", university: "华东师范大学" },
    { name: "社会心理学", university: "西安交通大学" },
    { name: "社会调查与研究方法", university: "北京大学" },
    { name: "神奇的材料世界", university: "武汉理工大学" },
    { name: "神经网络与深度学习", university: "西安科技大学" },
    { name: "科学研究方法与论文写作", university: "复旦大学" },
    { name: "中国税制", university: "江西财经大学" },
    { name: "简明中国史（一）", university: "武汉大学" },
    { name: "简明中国史（二）", university: "武汉大学" },
    { name: "管理学", university: "北方工业大学" },
    { name: "管理沟通", university: "华北电力大学" },
    { name: "纪录片创作理论与实践", university: "浙江大学" },
    { name: "纪录片制作", university: "北京师范大学" },
    { name: "纪录片制作", university: "北京师范大学" },
    { name: "纪录片制作", university: "北京师范大学" },
    { name: "纳米技术", university: "哈尔滨工业大学" },
    { name: "纳米技术", university: "哈尔滨工业大学" },
    { name: "线性代数", university: "东南大学" },
    { name: "组件地理信息系统", university: "首都师范大学" },
    { name: `管理素质与能力的五项修炼——跟我学"管理学"`, university: "中南大学" },
    { name: "细胞工程", university: "新乡医学院" },
    { name: "经典导读与欣赏", university: "西南大学" },
    { name: "网球教程", university: "东北大学" },
    { name: "美国文学（19世纪）", university: "哈尔滨师范大学" },
    { name: "美术欣赏", university: "北京师范大学" },
    { name: "大学生职业发展与就业指导", university: "福州大学" },
    { name: "职场口笔译", university: "福建师范大学" },
    { name: "能量转换与利用", university: "北京工业大学" },
    { name: "自我认知与情绪管理", university: "哈尔滨工业大学" },
    { name: "走进舞蹈艺术", university: "首都师范大学" },
    { name: "英国小说", university: "南京大学" },
    { name: "英国文学导读", university: "华中农业大学" },
    { name: "英语听力技能与实践", university: "集美大学" },
    { name: "英语教学与互联网", university: "爱课程" },
    { name: "英语演讲", university: "集美大学" },
    { name: "英语语音", university: "上海师范大学" },
    { name: "英语语音与信息沟通", university: "南京大学" },
    { name: "融合新闻：通往未来新闻之路", university: "暨南大学" },
    { name: "西方文学经典鉴赏", university: "北京师范大学" },
    { name: "西方风景园林艺术史", university: "上海交通大学" },
    { name: "计算机系统基础(一)：程序的表示、转换与链接", university: "南京大学" },
    { name: "计算机系统基础(三)：异常、中断和输入/输出", university: "南京大学" },
    { name: "计算机系统基础（二）：程序的执行和存储访问", university: "南京大学" },
    { name: "计算机网络", university: "华南理工大学" },
    { name: "计算物理基础", university: "北京师范大学" },
    { name: "计量地理学", university: "华东师范大学" },
    { name: "语文教学案例研究", university: "云南师范大学" },
    { name: "语文课程标准与教学设计", university: "西南大学" },
    { name: "发展心理学", university: "武汉大学" },
    { name: "语言学概论", university: "北京大学" },
    { name: "课程与教学论", university: "陕西师范大学" },
    { name: "财务管理", university: "上海对外经贸大学" },
    { name: "财务管理", university: "上海对外经贸大学" },
    { name: "财务管理", university: "华东交通大学" },
    { name: "货币银行学", university: "东北财经大学" },
    { name: "走近儿童的心理世界", university: "浙江大学" },
    { name: "跟着电影去旅游", university: "山东大学" },
    { name: "跟着电影去旅游", university: "山东大学" },
    { name: "软件工程", university: "北京大学" },
    { name: "软件测试", university: "南京大学" },
    { name: "软件的构造艺术——软件工程", university: "江西师范大学" },
    { name: "运筹学", university: "华中科技大学" },
    { name: "逻辑学导论", university: "西北大学" },
    { name: "逻辑学导论", university: "西北大学" },
    { name: "逻辑学导论", university: "西北大学" },
    { name: "道路规划与几何设计", university: "同济大学" },
    { name: "电子商务", university: "重庆大学" },
    { name: "酒店管理原理", university: "华南理工大学" },
    { name: "酒店运营管理", university: "北京联合大学" },
    { name: "电子商务那些事", university: "中南财经政法大学" },
    { name: "前厅服务与管理", university: "南京旅游职业学院" },
    { name: "量子力学Ⅰ", university: "上海交通大学" },
    { name: "钢琴教学法", university: "福建师范大学" },
    { name: "音乐奥秘解码——轻松学乐理", university: "中央音乐学院" },
    { name: "食品化学", university: "南昌大学" },
    { name: "食品工程原理", university: "江苏大学" },
    { name: "食品工艺学", university: "江南大学" },
    { name: "食品工艺学", university: "福建农林大学" },
    { name: "食品工艺学", university: "福建农林大学" },
    { name: "食品毒理学", university: "北京林业大学" },
    { name: "食品营养学（双语）", university: "南昌大学" },
    { name: "食品分析", university: "福建农林大学" },
    { name: "饭店信息系统", university: "浙江旅游职业学院" },
    { name: "马克思主义基本原理", university: "南京航空航天大学" },
    { name: "高分子化学", university: "北京化工大学" },
    { name: "高分子材料", university: "金陵科技学院" },
    { name: "高分子物理", university: "北京化工大学" },
    { name: "高等代数（上）", university: "电子科技大学" },
    { name: "微积分基础", university: "北京大学" },
    { name: "高等数学（一）", university: "国防科技大学" },
    { name: "高等数学（一）", university: "国防科技大学" },
    { name: "高等数学（三）", university: "国防科技大学" },
    { name: "高等数学（三）", university: "同济大学" },
    { name: "高等数学（三）", university: "国防科技大学" },
    { name: "高等数学（二）", university: "国防科技大学" },
    { name: "高等数学（二）", university: "同济大学" },
    { name: "高等数学（二）", university: "同济大学" },
    { name: "高等数学（二）", university: "国防科技大学" },
    { name: "高等数学（二）", university: "同济大学" },
    { name: "高等数学（五）", university: "国防科技大学" },
    { name: "高等数学（五）", university: "国防科技大学" },
    { name: "高等数学（四）", university: "国防科技大学" },
    { name: "高等数学（四）", university: "同济大学" },
    { name: "高等数学（四）", university: "国防科技大学" },
    { name: "高级英语（1）", university: "江南大学" },
    { name: "android智能手机编程", university: "国家开放大学" }
]
// const UNIVERSITY = "西南政法大学"
const MAX_CONCURRENT_TASKS = 5;
const SEARCHES_PER_TASK = 5;
const COOKIE = `EDUWEBDEVICE=07654f166aa44dce8d7fe4abeecc0324; Hm_lvt_77dc9a9d49448cf5e629e5bebaa5500b=1721177818; HMACCOUNT=8CBBE8804B15E262; WM_TID=FNPtgGC9OrZFBBARRQKR7f8keO9M4i%2FM; hasVolume=true; __yadk_uid=mgzu8h4rEW2WNrJGho9lYdmTne9IW0AH; videoVolume=0.21; hb_MA-A976-948FFA05E931_source=cn.bing.com; NTESSTUDYSI=4878e21de90145179bc25f1843391ba3; NTES_YD_SESS=l9J5Jtvv0x.PnnfU..Ct_BppFKb.s7H.ZToGLeIPLfaHMmy6MT5QSOvldGRdFa0QGIm86hCMKaNmR4mAsNjbeBY8FLBLS5Xu11kbAuGbSaiGcA137heOULKL_nT8Nnm9ggHll_IIE0P5OlGvTXDcYttejGRrTBG0_C8EBBdNoL5q7l0aKH.fiJxmXoIKsrDYqnKrA6pSy51kI5lEydppihemADFBgXt5k7dRWkvwG_2HY; NTES_YD_PASSPORT=J_7JFPWEdl80O38kUJbSWG16i.LBcz4IR50ayqQiUdc0Wh3VWELSHaTMq54qkKOS5YhQVwJWUK0QNEMtlUwnOm8ZVw1otUbJSvcTNVLuzHSs1qHD7kUgcIBkMTrpBa_YexPapuL158Iip0NCvWkskBOFaLdSHu75SSHyFoPX.5Lws.QMNtPJlDQWtge6WpRx.AJcY7M_VMA0iz7qsdJiQUV4e; NETEASE_WDA_UID=1421911993#|#1582349769670; STUDY_INFO="yd.8e21141e743443d9b@163.com|8|1421911993|1723513250673"; STUDY_SESS="hW1c75W8EyGlWHoR1fYsP9qeGwh2Uwm7N3F4+Ag9RIr4IGiXEgZJvErTLdHpMaIcVA8/QpWzv7+hmkekeuVdVIS/gGaLO7hQgKSCyzwcu4ffjyPgckHnld15pVaooPW/7zUVp720Yj2/SQJ2ENDamaZ+Kfm/R134oMzZBqS0U04Lhur2Nm2wEb9HcEikV+3FTI8+lZKyHhiycNQo+g+/oA=="; STUDY_PERSIST="Y9JihuynohzILvEBRka61bShqPpLYWwzWOT3ZQ27AXzD++Eoz4B4uMyM4/9LW5hHB0GGtqgzswL2koxbribOGrU1OhvJ5RhLocgfKra/7HXwm8KDazepgXl/2q7SD9eWK8drAReP6OXUOLt9XBcOJ2YYvB8pheV3XU1UPLH84hf4O/dPAsKoKXyOHjYpGosDXVg//h7sRRRJAz5VBR5IupFLiyRYUmTiP+jqHdWWLDnZgpjCC7Iso4RP9U87vJE8LtaQzUT1ovP2MqtW5+L3Hw+PvH8+tZRDonbf7gEH7JU="; Hm_lpvt_77dc9a9d49448cf5e629e5bebaa5500b=1723513253; WM_NI=E%2FF5aCneh3sAf4y49Voh7jX7fwG088tMjt7xcOJBvRztpnys1CceKVs1yqAEAMwleU3uz8OkQWH47IDiOkmXRdxddWhAqDDh59v4rJ23J6qLDTIZnrzpqSmB%2FgJK%2BGQvQ24%3D; WM_NIKE=9ca17ae2e6ffcda170e2e6eeb9ea4eed989cbbdb47818a8ea6d55f928f8aacdb5aaa9d88b1c2538bb1a8ade52af0fea7c3b92a87f18ad6e449aebba8d4f24ba6ecb7d5bc5eadb8f98bdb3da6a989d1bb34b893a695b674a19186a3f55abaacc08ffc79f39dad86ca5eb1efb792c44f8393b98de85ff1abb6d9ce61938988d5b64388b7818cf05492bcb885e75dac9fbfa5c764f7e7bad5f142f2ed86d7f448888c87bbed7abab0bfb4f04aedb986acaa4d93aa9fd3b737e2a3`
const OUTPUT_DIR = path.join(__dirname, 'output');


export interface CourseResult {
    courseName: string;
    courseId: string | null;
}

async function processCourses(): Promise<CourseResult[]> {
    const queue = courses;
    const results: CourseResult[] = [];

    async function processChunk(chunk: CourseWithUni[]): Promise<void> {
        for (const course of chunk) {
            const courseId = await getCourseIdBySearch(course.name, course.university, COOKIE);

            results.push({
                courseName: course.name,
                courseId
            });
            console.log(`课程 "${course.name}" 的 ID 是: ${courseId}`);
        }
    }

    async function processQueue(): Promise<void> {
        while (queue.length > 0) {
            const chunk = queue.splice(0, SEARCHES_PER_TASK);
            await processChunk(chunk);
        }
    }

    const tasks: Promise<void>[] = Array(MAX_CONCURRENT_TASKS).fill(null).map(() => processQueue());
    await Promise.all(tasks);

    return results;
}

function saveResults(results: CourseResult[]): void {
    if (!fs.existsSync(OUTPUT_DIR)) {
        fs.mkdirSync(OUTPUT_DIR, { recursive: true });
    }

    const timestamp = new Date().toISOString().replace(/:/g, '-');
    const filename = `course_results_${timestamp}.json`;
    const filePath = path.join(OUTPUT_DIR, filename);

    fs.writeFileSync(filePath, JSON.stringify(results, null, 2));
    console.log(`结果已保存到: ${filePath}`);
}

processCourses().then((results: CourseResult[]) => {
    console.log('所有课程搜索完成');
    saveResults(results);
}).catch((error: Error) => {
    console.error('处理过程中发生错误:', error);
});